### ISSUE TITLE
Can't make changes to the repository [updating website with SpeqS-4 info]

### ISSUE THREAD

**Issue by hansjovis** [GipHouse/giphouse.github.io#4]
Hello, I'm a manager of the SpeqS-4 team.

I'm trying to update the website, in a seperate branch, with the information on the SpeqS-4 project, as been asked in an email from the directors last week.
The problem is, I don't seem to have permission to add a new branch to the website's repository, so I can't make a pull request to add the changes from this branch to the main branch as asked.
There is the option to fork the repo into my own github, and make a pull request across the forks (if I'm correct), but that would be a bit overkill in my own opinion for such a small change.

Can I get access to the repository?

**Comment by mrngm** [comment]
Hi Hans,

Please use the somewhat more overkill 'pull request across forks'. Giving additional permissions is, in a way, also overkill, and, in general, using this way of pull requests is done in almost all projects on Github with 'external' developers.

You can use the fork button on the top right, and then add your forked repository as another remote locally: `git remote add fork git@github.com:hansjovis/giphouse.github.io.git`. Then you can push your branch with the edits using `git push -u fork branchname`.

**Comment by hansjovis** [comment]
I see your point, you don't want to give any external developers full access to a repository in which they can change what they like, when they like.
I will fork the repository and follow the steps as you described!
