### ISSUE TITLE
Where to replace project on "homepage"?

### ISSUE THREAD

**Issue by DanielRoeven** [GipHouse/giphouse.github.io#5]
The small GipHouse assignment requires us to:
"make changes to the homepage such that your project replaces an old project from last semester".

However, we cannot locate said homepage. Could you provide a little more detailed instructions?

Kind regards,

**Comment by mrngm** [comment]
Hi Daniel,

In https://github.com/GipHouse/giphouse.github.io/blob/master/index.html#L7 you can see that `index.html` includes a file called `portfolio.html`. In `_includes/` you can find the `portfolio.html` that is included there. It contains some code to dynamically determine what to show.

Your project page should be uploaded to `_posts` with a suitable filename (e.g. `2016-04-09-cgi.html`). In one of the older files you can look up the structure. Choose one of the files (projects) in `_posts` you would like to replace, and (eventually) `git rm` that file in the branch you're working on.

Do you have enough details to continue?

**Comment by mrngm** [comment]
Hi Daniel, have a look at what @hansjovis has done in #6, in case you're still struggling with getting the project page up and running.
